### ISSUE TITLE
Rename m_* variables to *

### ISSUE THREAD

**Issue by brianzhang01** [OxfordRSE/ASMC#27]
m_scalingBuffer, m_alphaBuffer, m_betaBuffer, m_allZeros, m_batchSize, etc. should be renamed to no longer have the m_? This wasn't in Pier's earlier code, could someone explain why the variables got renamed to m_?

**Comment by fcooper8472** [comment]
Looks like it was @martinjrobins who renamed them.

I assume because they are private members and prefixing `m` for private members is a fairly standard notation.
